#ifndef LEXER_H
#define LEXER_H
typedef enum { TOKEN_EOF, TOKEN_IMPORT, TOKEN_MAIN, TOKEN_INT,
               TOKEN_STRING,

               TOKEN_BOOL, TOKEN_TRUE, TOKEN_FALSE,
               TOKEN_BYTE, TOKEN_UBYTE, TOKEN_SHORT, TOKEN_USHORT, TOKEN_UINT, 
               TOKEN_LONG, TOKEN_ULONG, TOKEN_FLOAT, TOKEN_DOUBLE, TOKEN_VOID, TOKEN_WCHAR,
               TOKEN_MAP, TOKEN_STRUCT, TOKEN_ALIAS, TOKEN_VAR,
               TOKEN_IDENTIFIER,
               TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_DOT, TOKEN_COLON,
               TOKEN_IF, TOKEN_ELSE, TOKEN_RETURN, TOKEN_NUMBER, TOKEN_STRING_LITERAL,
               TOKEN_ASSIGN, TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_LBRACKET, TOKEN_RBRACKET,
               TOKEN_EQ, TOKEN_NEQ, TOKEN_GT, TOKEN_LT, TOKEN_GE, TOKEN_LE,
               TOKEN_NOT, TOKEN_CHAR_LITERAL, TOKEN_WCHAR_LITERAL,
               TOKEN_CONST, TOKEN_ENUM, TOKEN_UNION, 
               TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT, TOKEN_FALLTHROUGH,
               TOKEN_FOR, TOKEN_WHILE, TOKEN_DO, TOKEN_BREAK, TOKEN_CONTINUE, 
               TOKEN_METHOD, TOKEN_EXPORT, TOKEN_MODULE,
               TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT,
               TOKEN_AND, TOKEN_OR, TOKEN_XOR, TOKEN_TILDE, 
               TOKEN_LSHIFT, TOKEN_RSHIFT,
               TOKEN_LOGIC_AND, TOKEN_LOGIC_OR,
               TOKEN_PLUS_ASSIGN, TOKEN_MINUS_ASSIGN, TOKEN_STAR_ASSIGN, TOKEN_SLASH_ASSIGN,
                TOKEN_AND_ASSIGN, TOKEN_OR_ASSIGN, TOKEN_XOR_ASSIGN, 
                TOKEN_LSHIFT_ASSIGN, TOKEN_RSHIFT_ASSIGN, TOKEN_MOD_ASSIGN,
                TOKEN_INC, TOKEN_DEC, TOKEN_QUESTION,
               TOKEN_UNKNOWN } TokenType;

typedef struct { TokenType type; char text[128]; int line; } Token;
typedef struct { Token tokens[4096]; int count; } TokenList;
int lex_file(const char* filename, TokenList* out);
#endif
